# Generated by Django 5.1.3 on 2024-11-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='电商平台名称')),
                ('base_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='电商平台URL')),
            ],
        ),
    ]
