# Generated by Django 5.1.3 on 2024-11-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='platform',
            table='platform',
        ),
    ]
